In [4]:
import pandas as pd
from sqlalchemy import create_engine

In [5]:
data = pd.read_csv("WB_IDS_WIDEF (1).csv")

In [6]:
data.isnull().sum().reset_index()

             index       0
0             FREQ       0
1       FREQ_LABEL       0
2         REF_AREA       0
3   REF_AREA_LABEL       0
4        INDICATOR       0
..             ...     ...
79            2027  355622
80            2028  356089
81            2029  356716
82            2030  357077
83            2031  357543

[84 rows x 2 columns]

In [7]:
con = create_engine("mysql+pymysql://root:aditya@localhost:3306/Deb_data")

In [8]:
data.columns

Index(['FREQ', 'FREQ_LABEL', 'REF_AREA', 'REF_AREA_LABEL', 'INDICATOR',
       'INDICATOR_LABEL', 'UNIT_MEASURE', 'UNIT_MEASURE_LABEL',
       'COMP_BREAKDOWN_1', 'COMP_BREAKDOWN_1_LABEL', 'COMP_BREAKDOWN_2',
       'COMP_BREAKDOWN_2_LABEL', 'COMP_BREAKDOWN_3', 'COMP_BREAKDOWN_3_LABEL',
       'DATABASE_ID', 'DATABASE_ID_LABEL', 'UNIT_MULT', 'UNIT_MULT_LABEL',
       'OBS_STATUS', 'OBS_STATUS_LABEL', 'OBS_CONF', 'OBS_CONF_LABEL', '1970',
       '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979',
       '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988',
       '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024',
       '2025', '2026', '2027', '2028', '2029', '2030', '2031'],
      dtype='str')

In [9]:
data.head(10)

,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1,COMP_BREAKDOWN_1_LABEL,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
0,A,Annual,AFG,Afghanistan,WB_IDS_BN_CAB_XOKA_CD,Current account balance,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A,Annual,AFG,Afghanistan,WB_IDS_BX_GRT_EXTA_CD_DT,"Grants, excluding technical cooperation",USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,...,3.749710e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A,Annual,AFG,Afghanistan,WB_IDS_BX_GRT_TECH_CD_DT,Technical cooperation grants,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,...,2.264600e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A,Annual,AFG,Afghanistan,WB_IDS_BX_KLT_DINV_CD_DT,"Foreign direct investment, net inflows in repo...",USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A,Annual,AFG,Afghanistan,WB_IDS_BX_KLT_DREM_CD_DT,Primary income on FDI,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,A,Annual,AFG,Afghanistan,WB_IDS_BX_PEF_CD_DT,"Portfolio investment, equity (DRS)",USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,A,Annual,AFG,Afghanistan,WB_IDS_BX_TRF_PWKR_CD_DT,Personal transfers and compensation of employe...,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,...,3.200000e+08,320000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,A,Annual,AFG,Afghanistan,WB_IDS_DT_AMT_DIMF,IMF repurchases,USD,US dollars,WB_IDS_COUNTERPART_AREA_IMF,Counterpart Area: International Monetary Fund,...,5.018449e+06,4202254.6,6641264.4,30410282.6,87755386.8,99845976.3,97430971.1,95015965.9,71246947.7,13901843.5
8,A,Annual,AFG,Afghanistan,WB_IDS_DT_AMT_DIMF,IMF repurchases,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,...,5.018449e+06,4202254.6,6641264.4,30410282.6,87755386.8,99845976.3,97430971.1,95015965.9,71246947.7,13901843.5
9,A,Annual,AFG,Afghanistan,WB_IDS_DT_AMT_DLTF,"Principal repayments on external debt, long-te...",USD,US dollars,WB_IDS_COUNTERPART_AREA_ADB,Counterpart Area: Asian Dev. Bank,...,0.000000e+00,1692000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
data.DATABASE_ID.nunique()

1

In [11]:
data.COMP_BREAKDOWN_1_LABEL.nunique()

303

In [12]:
non_unique = []
for column in data.columns:
    print(column, data[column].nunique())
    if data [column].nunique()<2:
        non_unique.append(column)

FREQ 1
FREQ_LABEL 1
REF_AREA 134
REF_AREA_LABEL 134
INDICATOR 102
INDICATOR_LABEL 102
UNIT_MEASURE 7
UNIT_MEASURE_LABEL 7
COMP_BREAKDOWN_1 303
COMP_BREAKDOWN_1_LABEL 303
COMP_BREAKDOWN_2 6
COMP_BREAKDOWN_2_LABEL 6
COMP_BREAKDOWN_3 5
COMP_BREAKDOWN_3_LABEL 5
DATABASE_ID 1
DATABASE_ID_LABEL 1
UNIT_MULT 1
UNIT_MULT_LABEL 1
OBS_STATUS 1
OBS_STATUS_LABEL 1
OBS_CONF 1
OBS_CONF_LABEL 1
1970 13986
1971 15015
1972 16029
1973 17335
1974 18642
1975 19892
1976 21609
1977 23327
1978 24835
1979 26063
1980 27670
1981 29281
1982 30728
1983 31922
1984 32576
1985 33137
1986 33625
1987 33865
1988 34205
1989 42817
1990 42875
1991 42687
1992 42754
1993 42585
1994 43052
1995 42754
1996 42369
1997 41829
1998 41185
1999 40995
2000 40969
2001 41025
2002 40074
2003 39166
2004 38621
2005 37635
2006 36835
2007 35611
2008 35436
2009 34921
2010 34892
2011 33837
2012 33317
2013 33522
2014 32999
2015 32907
2016 32910
2017 33144
2018 33199
2019 33071
2020 34206
2021 33832
2022 32961
2023 32893
2024 4741
2025 4551
2026 4352
2027 4186
2028 4020
2029 3778
2030 3620
2031 3449

In [13]:
data.drop(columns= non_unique, inplace=True)

In [14]:
data.columns

Index(['REF_AREA', 'REF_AREA_LABEL', 'INDICATOR', 'INDICATOR_LABEL',
       'UNIT_MEASURE', 'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1',
       'COMP_BREAKDOWN_1_LABEL', 'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_2_LABEL',
       'COMP_BREAKDOWN_3', 'COMP_BREAKDOWN_3_LABEL', '1970', '1971', '1972',
       '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981',
       '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990',
       '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
       '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
       '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026',
       '2027', '2028', '2029', '2030', '2031'],
      dtype='str')

In [15]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 366193 entries, 0 to 366192
Data columns (total 74 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   REF_AREA                366193 non-null  str
 1   REF_AREA_LABEL          366193 non-null  str
 2   INDICATOR               366193 non-null  str
 3   INDICATOR_LABEL         366193 non-null  str
 4   UNIT_MEASURE            366193 non-null  str
 5   UNIT_MEASURE_LABEL      366193 non-null  str
 6   COMP_BREAKDOWN_1        366193 non-null  str
 7   COMP_BREAKDOWN_1_LABEL  366193 non-null  str
 8   COMP_BREAKDOWN_2        366193 non-null  str
 9   COMP_BREAKDOWN_2_LABEL  366193 non-null  str
 10  COMP_BREAKDOWN_3        366193 non-null  str
 11  COMP_BREAKDOWN_3_LABEL  366193 non-null  str
 12  1970                    171121 non-null  float64
 13  1971                    175127 non-null  float64
 14  1972                    178338 non-null  float64
 15  1973                    179949 non-null  float64
 16  1974                    181805 non-null  float64
 17  1975                    183764 non-null  float64
 18  1976                    185647 non-null  float64
 19  1977                    189371 non-null  float64
 20  1978                    194486 non-null  float64
 21  1979                    196308 non-null  float64
 22  1980                    199071 non-null  float64
 23  1981                    209894 non-null  float64
 24  1982                    211632 non-null  float64
 25  1983                    213465 non-null  float64
 26  1984                    216127 non-null  float64
 27  1985                    221116 non-null  float64
 28  1986                    221610 non-null  float64
 29  1987                    221003 non-null  float64
 30  1988                    221296 non-null  float64
 31  1989                    251889 non-null  float64
 32  1990                    250987 non-null  float64
 33  1991                    252976 non-null  float64
 34  1992                    264762 non-null  float64
 35  1993                    273530 non-null  float64
 36  1994                    276527 non-null  float64
 37  1995                    276835 non-null  float64
 38  1996                    276934 non-null  float64
 39  1997                    275813 non-null  float64
 40  1998                    276619 non-null  float64
 41  1999                    280362 non-null  float64
 42  2000                    279464 non-null  float64
 43  2001                    276207 non-null  float64
 44  2002                    274423 non-null  float64
 45  2003                    274103 non-null  float64
 46  2004                    275159 non-null  float64
 47  2005                    274508 non-null  float64
 48  2006                    276720 non-null  float64
 49  2007                    276043 non-null  float64
 50  2008                    276717 non-null  float64
 51  2009                    276917 non-null  float64
 52  2010                    276960 non-null  float64
 53  2011                    275976 non-null  float64
 54  2012                    276035 non-null  float64
 55  2013                    276232 non-null  float64
 56  2014                    281197 non-null  float64
 57  2015                    281345 non-null  float64
 58  2016                    280415 non-null  float64
 59  2017                    280653 non-null  float64
 60  2018                    280984 non-null  float64
 61  2019                    281831 non-null  float64
 62  2020                    283769 non-null  float64
 63  2021                    284380 non-null  float64
 64  2022                    283990 non-null  float64
 65  2023                    285173 non-null  float64
 66  2024                    12084 non-null   float64
 67  2025                    11392 non-null   float64
 68  2026                    10900 non-null   float64
 69  2027                    10571 non-null   float64
 70  2028                    10104 non-null   float64
 71  2029                    9477 non-null    float64
 72  2030                    9116 non-null    float64
 73  2031                    8650 non-null    float64
dtypes: float64(62), str(12)
memory usage: 206.7 MB

In [16]:
uniques = {}
for column in data.columns:
    if data[column].dtype == 'str':
        uniques[column] = data[column].unique()
    else:
        continue

In [17]:
uniques = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in uniques.items()]))
uniques.to_csv('uniques_IDA.csv')

In [18]:
column = data.columns
id_vars= column[:12]
value_vars = column[12:]

print(id_vars)
print(value_vars)

Index(['REF_AREA', 'REF_AREA_LABEL', 'INDICATOR', 'INDICATOR_LABEL',
       'UNIT_MEASURE', 'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1',
       'COMP_BREAKDOWN_1_LABEL', 'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_2_LABEL',
       'COMP_BREAKDOWN_3', 'COMP_BREAKDOWN_3_LABEL'],
      dtype='str')
Index(['1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978',
       '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023',
       '2024', '2025', '2026', '2027', '2028', '2029', '2030', '2031'],
      dtype='str')

In [19]:
df_long = pd.melt(data,
    id_vars= id_vars,
    value_vars= value_vars,
    var_name='Year',
    value_name='Value'

)
print (df_long)

         REF_AREA REF_AREA_LABEL                 INDICATOR  \
0             AFG    Afghanistan     WB_IDS_BN_CAB_XOKA_CD
1             AFG    Afghanistan  WB_IDS_BX_GRT_EXTA_CD_DT
2             AFG    Afghanistan  WB_IDS_BX_GRT_TECH_CD_DT
3             AFG    Afghanistan  WB_IDS_BX_KLT_DINV_CD_DT
4             AFG    Afghanistan  WB_IDS_BX_KLT_DREM_CD_DT
...           ...            ...                       ...
22703961      ZWE       Zimbabwe             WB_IDS_FI_RES
22703962      ZWE       Zimbabwe          WB_IDS_FI_RES_DT
22703963      ZWE       Zimbabwe          WB_IDS_FI_RES_MO
22703964      ZWE       Zimbabwe     WB_IDS_NY_GNP_MKTP_CD
22703965      ZWE       Zimbabwe        WB_IDS_SP_POP_TOTL

                                            INDICATOR_LABEL UNIT_MEASURE  \
0                                   Current account balance          USD
1                   Grants, excluding technical cooperation          USD
2                              Technical cooperation grants          USD
3         Foreign direct investment, net inflows in repo...          USD
4                                     Primary income on FDI          USD
...                                                     ...          ...
22703961                     Total reserves (includes gold)          USD
22703962                                     Total reserves    PT_DB_EXT
22703963                Total reserves in months of imports            M
22703964                                                GNI          USD
22703965                                  Population, total        COUNT

                   UNIT_MEASURE_LABEL             COMP_BREAKDOWN_1  \
0                          US dollars  WB_IDS_COUNTERPART_AREA_WLD
1                          US dollars  WB_IDS_COUNTERPART_AREA_WLD
2                          US dollars  WB_IDS_COUNTERPART_AREA_WLD
3                          US dollars  WB_IDS_COUNTERPART_AREA_WLD
4                          US dollars  WB_IDS_COUNTERPART_AREA_WLD
...                               ...                          ...
22703961                   US dollars  WB_IDS_COUNTERPART_AREA_WLD
22703962  Percentage of external debt  WB_IDS_COUNTERPART_AREA_WLD
22703963                       Months  WB_IDS_COUNTERPART_AREA_WLD
22703964                   US dollars  WB_IDS_COUNTERPART_AREA_WLD
22703965                        Count  WB_IDS_COUNTERPART_AREA_WLD

           COMP_BREAKDOWN_1_LABEL COMP_BREAKDOWN_2 COMP_BREAKDOWN_2_LABEL  \
0         Counterpart Area: World               _Z         Not Applicable
1         Counterpart Area: World               _Z         Not Applicable
2         Counterpart Area: World               _Z         Not Applicable
3         Counterpart Area: World               _Z         Not Applicable
4         Counterpart Area: World               _Z         Not Applicable
...                           ...              ...                    ...
22703961  Counterpart Area: World               _Z         Not Applicable
22703962  Counterpart Area: World               _Z         Not Applicable
22703963  Counterpart Area: World               _Z         Not Applicable
22703964  Counterpart Area: World               _Z         Not Applicable
22703965  Counterpart Area: World               _Z         Not Applicable

         COMP_BREAKDOWN_3 COMP_BREAKDOWN_3_LABEL  Year  Value
0                      _Z         Not Applicable  1970    NaN
1                      _Z         Not Applicable  1970    NaN
2                      _Z         Not Applicable  1970    NaN
3                      _Z         Not Applicable  1970    NaN
4                      _Z         Not Applicable  1970    NaN
...                   ...                    ...   ...    ...
22703961               _Z         Not Applicable  2031    NaN
22703962               _Z         Not Applicable  2031    NaN
22703963               _Z         Not Applicable  2031    NaN
22703964               _Z         Not Applicable  2031    NaN
22703965               _Z         Not Applicable  2031    NaN

[22703966 rows x 14 columns]

In [20]:
df_long.head()

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3,COMP_BREAKDOWN_3_LABEL,Year,Value
0,AFG,Afghanistan,WB_IDS_BN_CAB_XOKA_CD,Current account balance,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,NaN
1,AFG,Afghanistan,WB_IDS_BX_GRT_EXTA_CD_DT,"Grants, excluding technical cooperation",USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,NaN
2,AFG,Afghanistan,WB_IDS_BX_GRT_TECH_CD_DT,Technical cooperation grants,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,NaN
3,AFG,Afghanistan,WB_IDS_BX_KLT_DINV_CD_DT,"Foreign direct investment, net inflows in repo...",USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,NaN
4,AFG,Afghanistan,WB_IDS_BX_KLT_DREM_CD_DT,Primary income on FDI,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,NaN

In [21]:
df_long.shape

(22703966, 14)

In [22]:
data.columns

Index(['REF_AREA', 'REF_AREA_LABEL', 'INDICATOR', 'INDICATOR_LABEL',
       'UNIT_MEASURE', 'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1',
       'COMP_BREAKDOWN_1_LABEL', 'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_2_LABEL',
       'COMP_BREAKDOWN_3', 'COMP_BREAKDOWN_3_LABEL', '1970', '1971', '1972',
       '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981',
       '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990',
       '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
       '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
       '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026',
       '2027', '2028', '2029', '2030', '2031'],
      dtype='str')

In [23]:
uniques = {}
for col in data.columns:
       uniques[col] = data[col].unique()

In [24]:
uniques

{'REF_AREA': <StringArray>
 ['AFG', 'AGO', 'ALB', 'ARG', 'ARM', 'AZE', 'BDI', 'BEN', 'BFA', 'BGD',
  ...
  'UZB', 'VCT', 'VNM', 'VUT', 'WSM', 'XKX', 'YEM', 'ZAF', 'ZMB', 'ZWE']
 Length: 134, dtype: str,
 'REF_AREA_LABEL': <StringArray>
 [                   'Afghanistan',                         'Angola',
                         'Albania',                      'Argentina',
                         'Armenia',                     'Azerbaijan',
                         'Burundi',                          'Benin',
                    'Burkina Faso',                     'Bangladesh',
  ...
                      'Uzbekistan', 'St. Vincent and the Grenadines',
                        'Viet Nam',                        'Vanuatu',
                           'Samoa',                         'Kosovo',
                     'Yemen, Rep.',                   'South Africa',
                          'Zambia',                       'Zimbabwe']
 Length: 134, dtype: str,
 'INDICATOR': <StringArray>
 [   'WB_IDS_BN_CAB_XOKA_CD', 'WB_IDS_BX_GRT_EXTA_CD_DT',
  'WB_IDS_BX_GRT_TECH_CD_DT', 'WB_IDS_BX_KLT_DINV_CD_DT',
  'WB_IDS_BX_KLT_DREM_CD_DT',      'WB_IDS_BX_PEF_CD_DT',
  'WB_IDS_BX_TRF_PWKR_CD_DT',       'WB_IDS_DT_AMT_DIMF',
        'WB_IDS_DT_AMT_DLTF',            'WB_IDS_DT_AXA',
  ...
         'WB_IDS_DT_PCBK_PS',            'WB_IDS_DT_PPG',
            'WB_IDS_DT_PRVG',             'WB_IDS_DT_PS',
             'WB_IDS_DT_TDS',       'WB_IDS_DT_PBND_OPS',
            'WB_IDS_DT_PNGB',        'WB_IDS_DT_MLT_OPS',
       'WB_IDS_DT_PBND_PRVG',       'WB_IDS_DT_MLT_PRVG']
 Length: 102, dtype: str,
 'INDICATOR_LABEL': <StringArray>
 [                                          'Current account balance',
                            'Grants, excluding technical cooperation',
                                       'Technical cooperation grants',
  'Foreign direct investment, net inflows in reporting economy (DRS)',
                                              'Primary income on FDI',
                                 'Portfolio investment, equity (DRS)',
         'Personal transfers and compensation of employees, received',
                                                    'IMF repurchases',
             'Principal repayments on external debt, long-term + IMF',
                                        'Principal arrears creditors',
  ...
                               'Public sector debt, commercial banks',
                           'Public and publicly guaranteed creditors',
                      'Private Guaranteed by Public Sector creditors',
                                            'Public sector creditors',
                                      'Debt service on external debt',
                                    'Other public sector debt, bonds',
                                       'Private non-guaranteed,bonds',
                             'Other public sector debt, multilateral',
                    'Private Guaranteed by Public Sector debt, bonds',
             'Private Guaranteed by Public Sector debt, multilateral']
 Length: 102, dtype: str,
 'UNIT_MEASURE': <StringArray>
 ['USD', 'PT', 'PT_DB_EXT', 'PT_GNI', 'YR', 'M', 'COUNT']
 Length: 7, dtype: str,
 'UNIT_MEASURE_LABEL': <StringArray>
 [                 'US dollars',                  'Percentage',
  'Percentage of external debt',           'Percentage of GNI',
                        'Years',                      'Months',
                        'Count']
 Length: 7, dtype: str,
 'COMP_BREAKDOWN_1': <StringArray>
 [ 'WB_IDS_COUNTERPART_AREA_WLD',  'WB_IDS_COUNTERPART_AREA_IMF',
   'WB_IDS_COUNTERPART_AREA_ADB',  'WB_IDS_COUNTERPART_AREA_BGR',
   'WB_IDS_COUNTERPART_AREA_FCW',  'WB_IDS_COUNTERPART_AREA_GFR',
   'WB_IDS_COUNTERPART_AREA_IDA',  'WB_IDS_COUNTERPART_AREA_IRQ',
  'WB_IDS_COUNTERPART_AREA_ISDB', 'WB_IDS_COUNTERPART_AREA_OPEC',
  ...
  'WB_IDS_COUNTERPART_AREA_WIPO',  'WB_IDS_COUNTERPART_AREA_WMO',
   'WB_IDS_COUNTERPART_AREA_WSM',  'WB_IDS_COUNTERPART_AREA_WTO',
   'WB_IDS_COUNTERPART_AREA_XKX',  'WB_IDS_COUNTERPART_AREA_YEM',
   'WB_IDS_COUNTERPART_AREA_YUG',  'WB_IDS_COUNTERPART_AREA_ZAF',
   'WB_IDS_COUNTERPART_AREA_ZMB',  'WB_IDS_COUNTERPART_AREA_ZWE']
 Length: 303, dtype: str,
 'COMP_BREAKDOWN_1_LABEL': <StringArray>
 [                                      'Counterpart Area: World',
                  'Counterpart Area: International Monetary Fund',
                              'Counterpart Area: Asian Dev. Bank',
                                     'Counterpart Area: Bulgaria',
                       'Counterpart Area: Other Multiple Lenders',
                        'Counterpart Area: Germany, Fed. Rep. of',
                               'Counterpart Area: World Bank-IDA',
                                         'Counterpart Area: Iraq',
                            'Counterpart Area: Islamic Dev. Bank',
             'Counterpart Area: OPEC Fund for International Dev.',
  ...
  'Counterpart Area: UN-World Intellectual Property Organization',
         'Counterpart Area: UN-World Meteorological Organization',
                                        'Counterpart Area: Samoa',
                     'Counterpart Area: World Trade Organization',
                                       'Counterpart Area: Kosovo',
                           'Counterpart Area: Yemen, Republic Of',
                                   'Counterpart Area: Yugoslavia',
                                 'Counterpart Area: South Africa',
                                       'Counterpart Area: Zambia',
                                     'Counterpart Area: Zimbabwe']
 Length: 303, dtype: str,
 'COMP_BREAKDOWN_2': <StringArray>
 [                     '_Z', 'WB_IDS_CREDITOR_COV_PRV',
         'WB_IDS_STOCK_TDS',  'WB_IDS_DEBTOR_COV_PRVG',
    'WB_IDS_DEBTOR_COV_PRV', 'WB_IDS_CREDITOR_COV_MLT']
 Length: 6, dtype: str,
 'COMP_BREAKDOWN_2_LABEL': <StringArray>
 [                                      'Not Applicable',
                  'Creditor Coverage: Private Creditors',
                     'Stock/Flow: Debt service payments',
  'Debtor Coverage: Private Guaranteed by Public Sector',
                       'Debtor Coverage: Private sector',
             'Creditor Coverage: Multilateral Creditors']
 Length: 6, dtype: str,
 'COMP_BREAKDOWN_3': <StringArray>
 [                     '_Z',        'WB_IDS_CONCESN_C',
       'WB_IDS_MATURITY_LT', 'WB_IDS_CREDITOR_COV_PRV',
        'WB_IDS_CONCESN_NC']
 Length: 5, dtype: str,
 'COMP_BREAKDOWN_3_LABEL': <StringArray>
 [                      'Not Applicable',
            'Concessional: Concessional',
                   'Maturity: Long-term',
  'Creditor Coverage: Private Creditors',
         'Concessional: Nonconcessional']
 Length: 5, dtype: str,
 '1970': array([           nan, 2.00000000e+04, 9.00000000e+04, ...,
        2.44402541e+01, 1.74894111e+09, 5.21591800e+06], shape=(13987,)),
 '1971': array([           nan, 1.00000000e+04, 7.00000000e+04, ...,
        1.52958816e+01, 1.98290383e+09, 5.37471200e+06], shape=(15016,)),
 '1972': array([           nan, 3.00000000e+04, 6.00000000e+04, ...,
        3.76789401e+01, 2.45164329e+09, 5.54244500e+06], shape=(16030,)),
 '1973': array([           nan, 8.00000000e+04, 7.54000000e+06, ...,
        7.15736755e+01, 3.06136742e+09, 5.72040400e+06], shape=(17336,)),
 '1974': array([           nan, 2.80000000e+05, 9.00000000e+04, ...,
        4.30763200e+01, 3.64271018e+09, 5.90832800e+06], shape=(18643,)),
 '1975': array([           nan, 4.56000000e+06, 2.00000000e+05, ...,
        5.02904356e+01, 3.96550512e+09, 6.09865800e+06], shape=(19893,)),
 '1976': array([           nan, 1.19200000e+07, 5.56000000e+06, ...,
        6.06948864e+01, 3.84816443e+09, 6.28710500e+06], shape=(21610,)),
 '1977': array([           nan, 1.29900000e+07, 1.85500000e+07, ...,
        9.37772772e-01, 3.88143062e+09, 6.44951200e+06], shape=(23328,)),
 '1978': array([           nan, 3.49000000e+07, 1.04600000e+07, ...,
        1.88764934e+00, 3.96930564e+09, 6.54357500e+06], shape=(24836,)),
 '1979': array([           nan, 2.92100000e+07, 1.44100000e+07, ...,
        2.88443348e+00, 4.67153151e+09, 6.64755600e+06], shape=(26064,)),
 '1980': array([           nan, 3.20200000e+07, 1.55000000e+07, ...,
        2.06712581e+00, 5.71912946e+09, 7.04130300e+06], shape=(27671,)),
 '1981': array([           nan, 3.75600000e+07, 1.73000000e+07, ...,
        1.41261964e+00, 7.17401785e+09, 7.49863500e+06], shape=(29282,)),
 '1982': array([           nan, 3.17800000e+07, 1.87600000e+07, ...,
        1.22182088e+00, 7.08291198e+09, 7.79649600e+06], shape=(30729,)),
 '1983': array([           nan, 3.30500000e+07, 2.40500000e+07, ...,
        1.27840249e+00, 6.48739547e+09, 8.09840400e+06], shape=(31923,)),
 '1984': array([           nan, 5.36400000e+07, 2.19500000e+07, ...,
        1.23230861e+00, 5.56245480e+09, 8.39148800e+06], shape=(32577,)),
 '1985': array([           nan, 1.95000000e+08, 4.43300000e+07, ...,
        1.71434251e+00, 4.82566815e+09, 8.68681300e+06], shape=(33138,)),
 '1986': array([            nan, -3.03000000e+08,  5.74600000e+07, ...,
         1.67206631e+00,  5.03234297e+09,  8.98257800e+06], shape=(33626,)),
 '1987': array([           nan, 4.47000000e+08, 6.53700000e+07, ...,
        1.92541533e+00, 5.36279838e+09, 9.28464400e+06], shape=(33866,)),
 '1988': array([            nan, -4.69000000e+08,  9.72000000e+07, ...,
         1.70997631e+00,  6.26889619e+09,  9.58309400e+06], shape=(34206,)),
 '1989': array([            nan, -1.32000000e+08,  1.03470000e+08, ...,
         1.05457496e+00,  6.91434718e+09,  9.86479800e+06], shape=(42818,)),
 '1990': array([            nan, -2.35500000e+08,  1.92090000e+08, ...,
         1.14791131e+00,  7.03180976e+09,  1.01372810e+07], shape=(42876,)),
 '1991': array([            nan, -5.79600000e+08,  1.88780000e+08, ...,
         1.02326981e+00,  6.68335700e+09,  1.04048160e+07], shape=(42688,)),
 '1992': array([            nan, -7.34776000e+08,  1.85730000e+08, ...,
         1.35626224e+00,  4.94551250e+09,  1.07027000e+07], shape=(42755,)),
 '1993': array([            nan, -6.68500000e+08,  1.69810000e+08, ...,
         2.62365584e+00,  4.96639580e+09,  1.08602880e+07], shape=(42586,)),
 '1994': array([            nan, -3.39800000e+08,  3.00660000e+08, ...,
         2.09421749e+00,  4.98407990e+09,  1.08731480e+07], shape=(43053,)),
 '1995': array([            nan, -2.95047000e+08,  3.27800000e+08, ...,
         1.44697115e+01,  5.01143960e+09,  1.09745990e+07], shape=(42755,)),
 '1996': array([           nan, 3.26637800e+09, 2.75510000e+08, ...,
        1.41000984e+01, 6.49840390e+09, 1.11583600e+07], shape=(42370,)),
 '1997': array([            nan, -8.83540000e+08,  2.42020000e+08, ...,
         4.35184107e+00,  5.92088580e+09,  1.13698270e+07], shape=(41830,)),
 '1998': array([            nan, -1.86713000e+09,  2.16040000e+08, ...,
         4.55259646e+00,  3.92210640e+09,  1.15942970e+07], shape=(41186,)),
 '1999': array([            nan, -1.71041000e+09,  2.61120000e+08, ...,
         8.44170458e+00,  4.56952510e+09,  1.17834580e+07], shape=(40996,)),
 '2000': array([          nan, 7.9565000e+08, 2.0604000e+08, ..., 6.0796416e+00,
        4.3643696e+09, 1.1892055e+07], shape=(40970,)),
 '2001': array([            nan, -1.43093000e+09,  2.13430000e+08, ...,
         2.46640311e+00,  4.65141200e+09,  1.19719010e+07], shape=(41026,)),
 '2002': array([            nan, -1.50093385e+08,  3.35560000e+08, ...,
         2.61744742e+00,  4.60436960e+09,  1.20876530e+07], shape=(40075,)),
 '2003': array([            nan, -7.19558880e+08,  4.12470000e+08, ...,
         2.31592039e+00,  4.31132020e+09,  1.22323230e+07], shape=(39167,)),
 '2004': array([           nan, 6.81237662e+08, 3.64870000e+08, ...,
        4.46089886e+00, 3.97920590e+09, 1.23658960e+07], shape=(38622,)),
 '2005': array([           nan, 5.13788265e+09, 3.03260000e+08, ...,
        2.39936670e+00, 3.98647080e+09, 1.24834320e+07], shape=(37636,)),
 '2006': array([1.44352949e+09, 2.01476000e+09, 8.43810000e+08, ...,
        3.30830527e+00, 3.42882130e+09, 1.26364450e+07], shape=(36836,)),
 '2007': array([5.42350906e+09, 3.93885000e+09, 5.16730000e+08, ...,
        2.63814572e+00, 2.95654500e+09, 1.28040580e+07], shape=(35612,)),
 '2008': array([-2.38376259e+08,  3.90378000e+09,  7.10960000e+08, ...,
         1.34866292e+00,  1.55987010e+09,  1.29591490e+07], shape=(35437,)),
 '2009': array([2.77627586e+08, 4.78434000e+09, 9.57300000e+08, ...,
        2.61352604e+00, 8.81104870e+09, 1.31427900e+07], shape=(34922,)),
 '2010': array([-5.77708207e+08,  5.42635000e+09,  8.93130000e+08, ...,
         1.33180705e+00,  1.10745625e+10,  1.33565480e+07], shape=(34893,)),
 '2011': array([-2.24692117e+09,  5.87352000e+09,  8.49840000e+08, ...,
         8.31572576e-01,  1.25153569e+10,  1.35954240e+07], shape=(33838,)),
 '2012': array([-5.15016188e+09,  5.72016000e+09,  8.96900000e+08, ...,
         7.95379472e-01,  1.52458824e+10,  1.38178870e+07], shape=(33318,)),
 '2013': array([-5.09504060e+09,  4.33256000e+09,  8.23980000e+08, ...,
         6.56236844e-01,  1.72208724e+10,  1.40138080e+07], shape=(33523,)),
 '2014': array([-3.23289317e+09,  4.34624000e+09,  6.55640000e+08, ...,
         5.28425885e-01,  1.73004322e+10,  1.42073590e+07], shape=(33000,)),
 '2015': array([-4.19281642e+09,  3.85411000e+09,  4.67490000e+08, ...,
         6.86350248e-01,  1.76048795e+10,  1.43990130e+07], shape=(32908,)),
 '2016': array([-2.70846294e+09,  3.66515000e+09,  4.90400000e+08, ...,
         7.41706222e-01,  1.80025923e+10,  1.46002940e+07], shape=(32911,)),
 '2017': array([-3.55489794e+09,  3.53289000e+09,  3.11920000e+08, ...,
         5.31003561e-01,  4.90835246e+10,  1.48124820e+07], shape=(33145,)),
 '2018': array([-3.89683760e+09,  3.53402000e+09,  3.00130000e+08, ...,
         1.31059263e-01,  3.34428990e+10,  1.50344520e+07], shape=(33200,)),
 '2019': array([-3.79193526e+09,  3.96388000e+09,  2.97060000e+08, ...,
         3.15468859e-01,  2.52615748e+10,  1.52713680e+07], shape=(33072,)),
 '2020': array([-3.13673335e+09,  3.58508000e+09,  3.27440000e+08, ...,
         6.84717540e-02,  2.63297447e+10,  1.55268880e+07], shape=(34207,)),
 '2021': array([           nan, 4.32913000e+09, 2.44120000e+08, ...,
        1.14824642e+00, 2.66217847e+10, 1.57972100e+07], shape=(33833,)),
 '2022': array([           nan, 3.74971000e+09, 2.26460000e+08, ...,
        7.02437729e-01, 3.20269411e+10, 1.60690560e+07], shape=(32962,)),
 '2023': array([           nan, 3.20000000e+08, 4.20225460e+06, ...,
        1.22868475e-01, 3.47960667e+10, 1.63408220e+07], shape=(32894,)),
 '2024': array([           nan, 6.64126440e+06, 1.10587100e+05, ...,
        8.46984900e+05, 3.63618430e+06, 1.32448088e+08], shape=(4742,)),
 '2025': array([           nan, 3.04102826e+07, 1.10587100e+05, ...,
        8.41618100e+05, 3.62618430e+06, 1.28663202e+08], shape=(4552,)),
 '2026': array([           nan, 8.77553868e+07, 1.10587100e+05, ...,
        8.36251500e+05, 3.60518430e+06, 1.20834048e+08], shape=(4353,)),
 '2027': array([           nan, 9.98459763e+07, 1.10587100e+05, ...,
        8.29543100e+05, 4.55918430e+06, 2.46665247e+08], shape=(4187,)),
 '2028': array([           nan, 9.74309711e+07, 1.10587100e+05, ...,
        8.22834800e+05, 5.00718430e+06, 2.31006448e+08], shape=(4021,)),
 '2029': array([       nan, 95015965.9,   110587.1, ...,   817468.1,  5443184.3,
        49135438.8], shape=(3779,)),
 '2030': array([       nan, 71246947.7,   110587.1, ...,   576414.8,  5370184.3,
        25088932.3], shape=(3621,)),
 '2031': array([       nan, 13901843.5,   577194.1, ...,   572389.8,  5296184.3,
        14863580.3], shape=(3450,))}

In [25]:
uniques = pd.DataFrame(dict([(k, pd.Series(v)) for k,v in uniques.items()]))

In [26]:
df_long.rename(columns ={"COMP_BREAKDOWN_1_LABEL" : "Counter_Part" , "COMP_BREAKDOWN_2_LABEL" : "Nature" , "COMP_BREAKDOWN_3_LABEL" : "Type"}, inplace =True)

In [27]:
data.columns = data.columns.str.strip()

In [28]:
df_long['COMP_BREAKDOWN_1_LABEL']  = data['COMP_BREAKDOWN_1_LABEL'].str.replace("Counterpart Area: ", "" )

In [29]:
df_long.drop(columns=['INDICATOR' , 'UNIT_MEASURE' , 'COMP_BREAKDOWN_1' , 'COMP_BREAKDOWN_2' , 'COMP_BREAKDOWN_3'], errors='ignore', inplace = True)

In [30]:
df_long.head(5)

,REF_AREA,REF_AREA_LABEL,INDICATOR_LABEL,UNIT_MEASURE_LABEL,Counter_Part,Nature,Type,Year,Value,COMP_BREAKDOWN_1_LABEL
0,AFG,Afghanistan,Current account balance,US dollars,Counterpart Area: World,Not Applicable,Not Applicable,1970,NaN,World
1,AFG,Afghanistan,"Grants, excluding technical cooperation",US dollars,Counterpart Area: World,Not Applicable,Not Applicable,1970,NaN,World
2,AFG,Afghanistan,Technical cooperation grants,US dollars,Counterpart Area: World,Not Applicable,Not Applicable,1970,NaN,World
3,AFG,Afghanistan,"Foreign direct investment, net inflows in repo...",US dollars,Counterpart Area: World,Not Applicable,Not Applicable,1970,NaN,World
4,AFG,Afghanistan,Primary income on FDI,US dollars,Counterpart Area: World,Not Applicable,Not Applicable,1970,NaN,World

In [32]:
#df_long.to_csv("data.csv")

In [ ]:
#from sqlalchemy import create_engine
#engine = create_engine("mysql+pymysql://root:9648@localhost/debt_data")

In [33]:
#df_long.to_sql(
#    name = "ida2",
#    con=engine,
#    index=False,
#    if_exists='replace',
#    chunksize=10000,
#    method='multi'
#)

In [34]:
df2_melt = pd.melt(
    data,
    id_vars=id_vars,
    value_vars= value_vars,
    var_name='Year',
    value_name='value'
    )

In [35]:
india_df = df2_melt[df2_melt['REF_AREA_LABEL'] == 'India']
india_df

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3,COMP_BREAKDOWN_3_LABEL,Year,value
138806,IND,India,WB_IDS_BN_CAB_XOKA_CD,Current account balance,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,NaN
138807,IND,India,WB_IDS_BX_GRT_EXTA_CD_DT,"Grants, excluding technical cooperation",USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,147350000.0
138808,IND,India,WB_IDS_BX_GRT_TECH_CD_DT,Technical cooperation grants,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,45890000.0
138809,IND,India,WB_IDS_BX_KLT_DINV_CD_DT,"Foreign direct investment, net inflows in repo...",USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,NaN
138810,IND,India,WB_IDS_BX_KLT_DREM_CD_DT,Primary income on FDI,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22480025,IND,India,WB_IDS_FI_RES,Total reserves (includes gold),USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,2031,NaN
22480026,IND,India,WB_IDS_FI_RES_DT,Total reserves,PT_DB_EXT,Percentage of external debt,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,2031,NaN
22480027,IND,India,WB_IDS_FI_RES_MO,Total reserves in months of imports,M,Months,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,2031,NaN
22480028,IND,India,WB_IDS_NY_GNP_MKTP_CD,GNI,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,2031,NaN
22480029,IND,India,WB_IDS_SP_POP_TOTL,"Population, total",COUNT,Count,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,2031,NaN

In [ ]:
#df2_melt['COMP_BREAKDOWN_1_LABEL'] = df2_melt['COMP_BREAKDOWN_1_LABEL'].str.replace('Counterpart Area: ','')

In [36]:
india_df.head(5)

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3,COMP_BREAKDOWN_3_LABEL,Year,value
138806,IND,India,WB_IDS_BN_CAB_XOKA_CD,Current account balance,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,NaN
138807,IND,India,WB_IDS_BX_GRT_EXTA_CD_DT,"Grants, excluding technical cooperation",USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,147350000.0
138808,IND,India,WB_IDS_BX_GRT_TECH_CD_DT,Technical cooperation grants,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,45890000.0
138809,IND,India,WB_IDS_BX_KLT_DINV_CD_DT,"Foreign direct investment, net inflows in repo...",USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,NaN
138810,IND,India,WB_IDS_BX_KLT_DREM_CD_DT,Primary income on FDI,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,1970,0.0

In [37]:
#india_df.columns

In [ ]:
#india_df.shape

(213962, 14)

In [38]:
data['Counterpart'] = data['COMP_BREAKDOWN_1_LABEL'].str.replace('Counterpart Area: ','', regex = False)

In [39]:
data.Counterpart.unique()

<StringArray>
[                                      'World',
                 'International Monetary Fund',
                             'Asian Dev. Bank',
                                    'Bulgaria',
                      'Other Multiple Lenders',
                       'Germany, Fed. Rep. of',
                              'World Bank-IDA',
                                        'Iraq',
                           'Islamic Dev. Bank',
            'OPEC Fund for International Dev.',
 ...
 'UN-World Intellectual Property Organization',
        'UN-World Meteorological Organization',
                                       'Samoa',
                    'World Trade Organization',
                                      'Kosovo',
                          'Yemen, Republic Of',
                                  'Yugoslavia',
                                'South Africa',
                                      'Zambia',
                                    'Zimbabwe']
Length: 303, dtype: str

sortred Indicator

In [40]:
data['Counterpart'].value_counts().head(50)

Counterpart
World                                            12401
France                                            6281
Germany, Fed. Rep. of                             6113
United States                                     5987
United Kingdom                                    5775
Japan                                             5366
Multiple Lenders                                  5293
Italy                                             5124
China                                             5002
Bondholders                                       4766
World Bank-IDA                                    4723
Belgium                                           4675
Netherlands                                       4514
Switzerland                                       4502
Austria                                           4496
Spain                                             4391
International Fund for Agricultural Dev.          4309
Kuwait                                            4168
Canada                                            4142
International Monetary Fund                       4128
European Investment Bank                          4056
OPEC Fund for International Dev.                  3933
Other Multiple Lenders                            3911
Sweden                                            3754
World Bank-IBRD                                   3740
Denmark                                           3735
Saudi Arabia                                      3575
India                                             3356
Russian Federation                                3220
Korea, Republic of                                3198
United Arab Emirates                              3166
Norway                                            2959
European Development Fund (EDF)                   2832
African Dev. Bank                                 2660
Finland                                           2645
Brazil                                            2623
USSR                                              2561
Islamic Dev. Bank                                 2520
Israel                                            2475
Serbia                                            2468
Czechia                                           2354
Poland                                            2308
Hungary                                           2292
Romania                                           2217
Australia                                         2204
German Dem. Rep.                                  2160
Luxembourg                                        2117
European Economic Community (EEC)                 2093
Czechoslovakia                                    2084
Arab Bank for Economic Dev. in Africa (BADEA)     1987
Name: count, dtype: int64

In [41]:
#data.columns

In [ ]:
data['INDICATOR_LABEL'].to_csv('indicator.csv', index=False)

In [42]:
india_df = data.loc[data['REF_AREA_LABEL'] == "India"]

In [43]:
india_df.head()

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2,COMP_BREAKDOWN_2_LABEL,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,Counterpart
138806,IND,India,WB_IDS_BN_CAB_XOKA_CD,Current account balance,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,...,-3.196229e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
138807,IND,India,WB_IDS_BX_GRT_EXTA_CD_DT,"Grants, excluding technical cooperation",USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
138808,IND,India,WB_IDS_BX_GRT_TECH_CD_DT,Technical cooperation grants,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
138809,IND,India,WB_IDS_BX_KLT_DINV_CD_DT,"Foreign direct investment, net inflows in repo...",USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,...,2.551979e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
138810,IND,India,WB_IDS_BX_KLT_DREM_CD_DT,Primary income on FDI,USD,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,...,4.657578e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World

In [44]:
data.drop(columns=['UNIT_MEASURE',], errors='ignore', inplace=True)

In [45]:
data.head(5)

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,Counterpart
0,AFG,Afghanistan,WB_IDS_BN_CAB_XOKA_CD,Current account balance,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
1,AFG,Afghanistan,WB_IDS_BX_GRT_EXTA_CD_DT,"Grants, excluding technical cooperation",US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
2,AFG,Afghanistan,WB_IDS_BX_GRT_TECH_CD_DT,Technical cooperation grants,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
3,AFG,Afghanistan,WB_IDS_BX_KLT_DINV_CD_DT,"Foreign direct investment, net inflows in repo...",US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
4,AFG,Afghanistan,WB_IDS_BX_KLT_DREM_CD_DT,Primary income on FDI,US dollars,WB_IDS_COUNTERPART_AREA_WLD,Counterpart Area: World,_Z,Not Applicable,_Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World

In [46]:
data.drop(columns=['COMP_BREAKDOWN_1',], errors='ignore', inplace=True)

In [47]:
data.head(5)

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3,COMP_BREAKDOWN_3_LABEL,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,Counterpart
0,AFG,Afghanistan,WB_IDS_BN_CAB_XOKA_CD,Current account balance,US dollars,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
1,AFG,Afghanistan,WB_IDS_BX_GRT_EXTA_CD_DT,"Grants, excluding technical cooperation",US dollars,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
2,AFG,Afghanistan,WB_IDS_BX_GRT_TECH_CD_DT,Technical cooperation grants,US dollars,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
3,AFG,Afghanistan,WB_IDS_BX_KLT_DINV_CD_DT,"Foreign direct investment, net inflows in repo...",US dollars,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
4,AFG,Afghanistan,WB_IDS_BX_KLT_DREM_CD_DT,Primary income on FDI,US dollars,Counterpart Area: World,_Z,Not Applicable,_Z,Not Applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World

In [48]:
data.drop(columns=['COMP_BREAKDOWN_3',], errors='ignore', inplace=True)

In [49]:
data.head(5)

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3_LABEL,1970,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,Counterpart
0,AFG,Afghanistan,WB_IDS_BN_CAB_XOKA_CD,Current account balance,US dollars,Counterpart Area: World,_Z,Not Applicable,Not Applicable,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
1,AFG,Afghanistan,WB_IDS_BX_GRT_EXTA_CD_DT,"Grants, excluding technical cooperation",US dollars,Counterpart Area: World,_Z,Not Applicable,Not Applicable,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
2,AFG,Afghanistan,WB_IDS_BX_GRT_TECH_CD_DT,Technical cooperation grants,US dollars,Counterpart Area: World,_Z,Not Applicable,Not Applicable,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
3,AFG,Afghanistan,WB_IDS_BX_KLT_DINV_CD_DT,"Foreign direct investment, net inflows in repo...",US dollars,Counterpart Area: World,_Z,Not Applicable,Not Applicable,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
4,AFG,Afghanistan,WB_IDS_BX_KLT_DREM_CD_DT,Primary income on FDI,US dollars,Counterpart Area: World,_Z,Not Applicable,Not Applicable,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World

In [50]:
data.drop(columns=['COMP_BREAKDOWN_2',], errors='ignore',inplace=True)

In [51]:
data["COMP_BREAKDOWN_1_LABEL"] = data['COMP_BREAKDOWN_1_LABEL'].str.replace("Counterpart Area: " , "")

In [52]:
data.columns

Index(['REF_AREA', 'REF_AREA_LABEL', 'INDICATOR', 'INDICATOR_LABEL',
       'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1_LABEL',
       'COMP_BREAKDOWN_2_LABEL', 'COMP_BREAKDOWN_3_LABEL', '1970', '1971',
       '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980',
       '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989',
       '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998',
       '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025',
       '2026', '2027', '2028', '2029', '2030', '2031', 'Counterpart'],
      dtype='str')

In [53]:
india_df.rename(columns={"COMP_BREAKDOWN_1_LABEL":"Counter_Part"}, inplace=True)

In [54]:
india_df.drop(columns=['COMP_BREAKDOWN_1',],errors='ignore',inplace=True)

In [55]:
india_df.drop(columns=['UNIT_MEASURE',],errors='ignore',inplace=True)

In [56]:
india_df.drop(columns=['COMP_BREAKDOWN_2',],errors='ignore',inplace=True)

In [57]:
india_df.drop(columns=['COMP_BREAKDOWN_3',],errors='ignore',inplace=True)

In [58]:
india_df.rename(columns={"COMP_BREAKDOWN_2_LABEL":"Nature" },inplace=True)

In [59]:
india_df.rename(columns={"COMP_BREAKDOWN_3_LABEL":"Type"},inplace=True)

In [60]:
india_df.head(5)

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE_LABEL,Counter_Part,Nature,Type,1970,1971,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,Counterpart
138806,IND,India,WB_IDS_BN_CAB_XOKA_CD,Current account balance,US dollars,Counterpart Area: World,Not Applicable,Not Applicable,NaN,NaN,...,-3.196229e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
138807,IND,India,WB_IDS_BX_GRT_EXTA_CD_DT,"Grants, excluding technical cooperation",US dollars,Counterpart Area: World,Not Applicable,Not Applicable,147350000.0,230260000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
138808,IND,India,WB_IDS_BX_GRT_TECH_CD_DT,Technical cooperation grants,US dollars,Counterpart Area: World,Not Applicable,Not Applicable,45890000.0,58320000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
138809,IND,India,WB_IDS_BX_KLT_DINV_CD_DT,"Foreign direct investment, net inflows in repo...",US dollars,Counterpart Area: World,Not Applicable,Not Applicable,NaN,NaN,...,2.551979e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
138810,IND,India,WB_IDS_BX_KLT_DREM_CD_DT,Primary income on FDI,US dollars,Counterpart Area: World,Not Applicable,Not Applicable,0.0,0.0,...,4.657578e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World

In [61]:
india_df.to_csv("India_unique_data.csv")

In [ ]:
data.rename(columns={"COMP_BREAKDOWN_1_LABEL":"Counter_Part"},inplace=True)

In [ ]:
data.rename(columns ={"COMP_BREAKDOWN_2_LABEL" : "Nature"}, inplace =True)

In [ ]:
data.rename(columns ={ "COMP_BREAKDOWN_3_LABEL": "Type"}, inplace =True)

In [ ]:
data.head()

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE_LABEL,Counter_Part,Nature,Type,1970,1971,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,Counterpart
0,AFG,Afghanistan,WB_IDS_BN_CAB_XOKA_CD,Current account balance,US dollars,World,Not Applicable,Not Applicable,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
1,AFG,Afghanistan,WB_IDS_BX_GRT_EXTA_CD_DT,"Grants, excluding technical cooperation",US dollars,World,Not Applicable,Not Applicable,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
2,AFG,Afghanistan,WB_IDS_BX_GRT_TECH_CD_DT,Technical cooperation grants,US dollars,World,Not Applicable,Not Applicable,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
3,AFG,Afghanistan,WB_IDS_BX_KLT_DINV_CD_DT,"Foreign direct investment, net inflows in repo...",US dollars,World,Not Applicable,Not Applicable,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World
4,AFG,Afghanistan,WB_IDS_BX_KLT_DREM_CD_DT,Primary income on FDI,US dollars,World,Not Applicable,Not Applicable,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,World

In [ ]:
import pandas as pd

df = pd.read_csv("India_unique_data.csv")
print(df.shape)

(3451, 72)

In [ ]:
#from sqlalchemy import create_engine

#engine= create_engine("mysql+pymysql://root:9648@localhost/debt_data")

In [ ]:
#engine= create_engine("mysql+pymysql://root:9648@localhost/debt_data")

In [ ]:
#con = create_engine("mysql+pymysql://root:aditya@localhost:3306/Debt_data")

In [ ]:
'''df.to_sql(
    name="india_data",
    con=engine,
    index=False,
    if_exists='replace',
    chunksize=10000
)'''

'df.to_sql(\n    name="india_data",\n    con=engine,\n    index=False,\n    if_exists=\'replace\',\n    chunksize=10000\n)'

In [ ]:
india_df.to_csv("IND.csv")

NameError: name 'india_df' is not defined